### ISSUE TITLE
Upgrade to python 3.11

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport-scorer#26]
Then we would be able to use: https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat
for parsing multiple formats of iso dates.

**Comment by nutrina** [comment]
Support for python 3.11 might not yet be available for siwe and web3: https://github.com/ethereum/web3.py/issues/2704

We might need an alternative to parsing the iso dates.

**Comment by aminah-io** [comment]
Looks like they added support for python 3.11 with this PR: https://github.com/ethereum/web3.py/pull/2699

**Comment by nutrina** [comment]
Yes, that right, python 3.11 seems to be officially supported, it is listed here: https://pypi.org/project/web3/6.0.0/
