### ISSUE TITLE
Move the gitcoin stamp data over from the web / cgrant DB to the scorer DB

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport-scorer#289]
To my knowledge the web product is about to be decommissioned soon.
We do however rely on an API in that product to verify the eligibility for the gitcoin stamps of the passport users.
We should therefore consider copying the relevant data over to the scorer DB.

Once you've migrated the data, rewrite the verification logic on the iam server to pull the data from this copy of the data in the scorer DB instead of the cgrants db which is being killed soon.

**Comment by Jeremy-Gitcoin** [comment]
Change the API endpoints to point to the new DB for Gitcoin grants stamp

**Comment by nutrina** [comment]
Open points:
- [ ] test the import functions
- [ ] add Bearer token auth to the API
- [ ] test the API
- [ ] release to prod
- [ ] import data into DB
- [ ] update API endpoints in Passport AMI

**Comment by lucianHymer** [comment]
To reset sequences: `python manage.py sqlsequencereset cgrants | python manage.py dbshell`

**Comment by lucianHymer** [comment]
Setting network:
```
to_update = Subscription.objects.filter(data__fields__network="mainnet")
to_update.update(is_mainnet=True)
```

**Comment by lucianHymer** [comment]
`Contribution.objects.filter(data__fields__success=True).update(success=True)`

**Comment by lucianHymer** [comment]
```
/usr/lib/postgresql/13/bin/pg_dump -Fd -a -t cgrants_contribution -t cgrants_subscription -j4 -f dumpdir_contr_subscr DB_URL

pg_restore -a -t cgrants_grantcontributionindex -j 16 -Fd -d DB_URL ../dumpdir
```

**Comment by Jeremy-Gitcoin** [comment]
Maintenance window on 5pm PT Mon 17th. This will have a banner / maintenance page

**Comment by lucianHymer** [comment]
@Jeremy-Gitcoin the real data is on staging, but on review I've just added dummy data for you and me. It should behave as if you donated $110 to one grant, so you'll get stamps for 1 donation, $10, and $100.
