### ISSUE TITLE
[Chore] Setup Redash within pulumi

### ISSUE THREAD

**Issue by digitalmnt** [gitcoinco/passport-scorer#315]
### User Story:
As a developer, 
I want the redash EC2 instance to be maintained via pulumi instead of a manual setup
To ensure the instance can be easily updated and deployed

### Acceptance Criteria
GIVEN I have valid AWS credentials,
WHEN I execute the Pulumi setup script,
THEN an EC2 instance should be created in AWS and the redash application should be hosted on it.

Maintenance and Updates via Pulumi:
GIVEN an update is made to the Pulumi script or the redash application,
WHEN the updated script or application is pushed via GitHub action,
THEN the EC2 instance and/or the redash instance hosted on it should be updated accordingly.

Domain Maintenance and Updates:
GIVEN there is a change to the domain associated with the redash application,
WHEN the Pulumi script reflecting the change is executed,
THEN the domain of the redash application hosted on the EC2 instance should be updated accordingly.

Product & Design Links:
n/a

Tech Details:
Use Pulumi to manage the AWS EC2 instance and the redash application hosted on it. Automate updates and deployments using GitHub actions.

Open Questions:
n/a

Notes/Assumptions:
This change will make the maintenance and deployment of the redash application more efficient and less error-prone.

**Comment by nutrina** [comment]
@digitalmnt also think about using a proper database, and not a local one. I mean what happens if somebody destroys the EC2 instance? I assume we would lose the data ....

**Comment by digitalmnt** [comment]
This sounds good to me. Yeah I believe we would lose the data

**Comment by digitalmnt** [comment]
Holding off on this until staging is free to test on
