### ISSUE TITLE
Implement Weekly Data Dumps via ECS Task

### ISSUE THREAD

**Issue by digitalmnt** [gitcoinco/passport-scorer#326]
**Description:**

In continuation of [Issue #1492](https://github.com/gitcoinco/passport/issues/1492), we aim to initiate weekly data dumps through an ECS task. The infrastructure files in [PR #324](https://github.com/gitcoinco/passport-scorer/pull/324) lay the groundwork for this scheduled ECS task. This ticket's objective is to ensure the necessary script is deployed across the intended environments before the resources are established.

**Key Points:**

- Deploy the script from PR #324 to the target environments.
- Once implemented, assess the export speeds, especially in light of the improvements made in [Issue #1525](https://github.com/gitcoinco/passport/issues/1525). We aim to determine if the exports are executed more efficiently.

**Action Required:** After the implementation, please evaluate the export speeds to ascertain if there's a noticeable improvement due to the changes in Issue #1525.

**Comment by nutrina** [comment]
@digitalmnt  shall we think about rather introducing airflow to handle this?

**Comment by nutrina** [comment]
@lucianHymer  once we get the infra setup working I would also add a more generic version of the current export script that would simply export all the data of a specific collection to S3 in an efficient way
We need this for for various data analysis tasks

**Comment by nutrina** [comment]
@erichfi  yes, this is ready to deploy
