### ISSUE TITLE
[CHORE] handle expired tokens in the UI

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport-scorer#33]
It can occur that a JWT token expires while being used to make API requests to the server.
We should be able to handle errors that are reported due a JWT token being expired.

This however is something that would occur very rarely.

**Comment by schultztimothy** [comment]
This is a bit hard to to test. If you login to the scorer then manipulate the `access-token` found in localstorage with the dev console then refresh the page you, or try to rename or delete a scorer or api key you should be logged out. Happy to pair on it as well. 



![Image](https://user-images.githubusercontent.com/6887938/229648726-accf52ad-4cc4-4990-9149-045f8c598cd5.png)
