### ISSUE TITLE
When reading a score the individual "points" are returned as null

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport-scorer#417]
The problem:

For example, when submitting a passport for scoring using the django ninja request handler, points is always returned a null.
This has to do with a confusion introduced by 1 schema:

```py

class DetailedScoreResponse(Schema):
    address: str
    score: Optional[str]
    status: Optional[StatusEnum]
    last_score_timestamp: Optional[str]
    evidence: Optional[ThresholdScoreEvidenceResponse]
    error: Optional[str]
    stamp_scores: Optional[Dict]

    @staticmethod
    def resolve_last_score_timestamp(obj):
        if obj.last_score_timestamp:
            return obj.last_score_timestamp.isoformat()
        return None

    @staticmethod
    def resolve_address(obj):
        return obj.passport.address
```

There is a field that is not named as in the model: `stamp_scores`.
And we have code that relies that the naming matches the one in the model, for example:
```py
async def a_submit_passport(
    request, payload: SubmitPassportPayload
) -> DetailedScoreResponse:
    check_rate_limit(request)
    try:
        log.error("/submit-passport, payload=%s", payload)

        if not request.api_key.submit_passports:
            raise InvalidAPIKeyPermissions()

        return await ahandle_submit_passport(payload, request.auth)
    except APIException as e:
        raise e
    except Exception as e:
        log.exception("Error submitting passport: %s", e)
        raise InternalServerErrorException("Unexpected error while submitting passport")
```

![Image](https://github.com/gitcoinco/passport-scorer/assets/8137830/c979d44f-189f-4c52-84d7-81b864087726)

Tasks:
- [ ] we should probably try to reduce the number of structures that we use (we might drop `ScoreData` in favour of `DetailedScoreResponse`
- [ ] stick to a naming convention, like: `DetailedScoreResponse` needs to have the same fields as the `Score` model for easier (automatic) mapping of fields

**Comment by digitalmnt** [comment]
pr is ready for this, just waitin on review and clarification of filters https://discord.com/channels/562828676480237578/1073190200404103218/1163533145535164467
