### ISSUE TITLE
[CHORE] Enable cypress tests in Github Actions

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport-scorer#44]
This is not about integrating Cypress with Github Actions. Figure out how to test the Blocknative Wallet Component with Cypress.

**Comment by aminah-io** [comment]
Is this the same as this issue?: https://github.com/gitcoinco/passport/issues/997

**Comment by schultztimothy** [comment]
It looks like this is the same one as: https://github.com/gitcoinco/passport/issues/997 I'm going to close out https://github.com/gitcoinco/passport/issues/997

**Comment by schultztimothy** [comment]
@nutrina I implemented https://github.com/gitcoinco/passport-scorer/pull/210 which just uses an environment variable to not logout a connected user if it is being ran during a cypress test. Happy to revisit this approach, but it seemed like a simple solution to allow us to test the majority of the application
