### ISSUE TITLE
Efficient ECS Task Sizing and Autoscaling

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport-scorer#449]
### User Story:
As a passport operator,
I want to ensure optimal sizing of all ECS tasks,
So that we maximize resource utilization while minimizing costs.

### Acceptance Criteria
GIVEN I am a passport developer/dev-ops,
WHEN the passport-scorer is live in production,
THEN the average CPU and memory utilization should remain at a minimum of 50%.

#### Tech Details:

- Review settings for all our ECS tasks.
- Adjust sizing and autoscaling thresholds as needed.
- Ensure CPU threshold for autoscaling remains above 50%.

#### Open Questions:

- How frequently should ECS task sizing be reviewed?
- Are there specific benchmarks or metrics that should be monitored regularly?

#### Notes/Assumptions:

- Proper task sizing and autoscaling will lead to cost savings.
- Monitoring service/container insights will give insights into utilization and performance.

**Comment by lucianHymer** [comment]
For the IAM task, I already took care of this as part of the last load testing!

**Comment by nutrina** [comment]
Downsizing targets for scorer:
- [ ] scorer-api-default: 1vCPU and 2GB Mem
  - [ ] autoscaling - minimum 2 instance
  - [ ] autoscaling CPU target: 50%
- [ ] scorer-staking-indexer: 0.5 vCPU and 1GB Mem
- [ ] scorer-api-reg: 2vCPU and 4GB Mem:
  - [ ] autoscaling - minimum 2 instance
  - [ ] autoscaling CPU target: 50%

**Comment by nutrina** [comment]
Have also removed unused resources like flower & the celery workers.
Also added tags to more of the resources that we initialise.

**Comment by aminah-io** [comment]
Blocked until we run pulumi preview on production
