### ISSUE TITLE
Move synthetic tests from DDog to UptimeRobot

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport-scorer#450]
Synthetic tests are a big block of our costs in ddog.
I think uptime robot is a cheaper alternative.

Actions:
- [ ] verify the uptime robot pricing, confirm the potential cost savings
- [ ] check that we can cover all synthetic tests with uptime robot (GET / POST / PATCH requests, authenticated requests ...)
- [ ] move tests to uptime robot 

Alternatively:
- tweak the setup on datadog (for example change the frequency from 1 min to 5 min)

**Comment by digitalmnt** [comment]
-  verify the uptime robot pricing, confirm the potential cost savings - $29 / month - https://uptimerobot.com/pricing/ - this should cover everything we are currently testing with our synthetic alarms, with the exception of aws specific region testing(which imo is ok to go without)
- check that we can cover all synthetic tests with uptime robot (GET / POST / PATCH requests, authenticated requests ...) we should be able to cover all existing tests
- move tests to uptime robot - Blocked - just need to get payment setup on the account and I can move the remaining tests over
- PagerDuty - with the $29/month account we can integrate all alerts with Pager Duty

**Comment by nutrina** [comment]
@aminah-io  please also update this document with the new monitors in Uptimerobot: https://www.notion.so/gitcoin/Passport-Monitors-444bfbe603d146ecbdd54211e1646957
